import { resolve } from 'node:path';
import { env } from '$env/dynamic/private';

// Where all persistent data lives. In Docker this is /data (set in the Dockerfile).
export const DATA_DIR = resolve(process.env.DATA_DIR ?? './data');

export const DB_PATH = resolve(DATA_DIR, 'hdpantry.db');

// SQL migration files generated by drizzle-kit (npm run db:generate).
export const MIGRATIONS_DIR = resolve(process.env.MIGRATIONS_DIR ?? './drizzle');

// Signs the login sessions. Throws at startup if SECRET is missing or too short.
export function getSecret() {
	const secret = env.SECRET;
	if (!secret || secret.length < 32) {
		throw new Error('SECRET must be set in .env and be at least 32 characters long');
	}
	return secret;
}
